#!/usr/bin/env ruby

begin
  config = File.open(".keet").read
rescue
  puts "No .keet file found."
end

eval(config)

def execute_profile(profile)
  os = `uname -s`.strip
  profiles = PROFILES.map(&:downcase)
  commands = COMMANDS.map { |key, value| [key.downcase, value] }

  if profiles.include? profile
    if COMMANDS[profile].has_key? os
      COMMANDS[profile][os].each do |command|
        puts "\n=> #{command}"
        begin
          cmd = system(command, exception: true)
        rescue Exception => e
          puts "\n\e[41m COMMAND FAILED \e[0m -> '#{e.message}'"
          exit 1
        end
      end
    else
      puts "Unsupported platform"
    end
  else
    puts "Invalid profile..."
  end
end

if ARGV.length == 0
  puts GREET
  puts "What profile would you like to use?\n\n"
  PROFILES.each_with_index do |profile, index|
    puts "#{index} -> #{profile}"
  end

  print "\nProfile -> "
  profile = gets.strip

  if /([A-Z])\w+/.match(profile) != ""
    profile = PROFILES[profile.to_i].downcase
    puts "Executing #{profile} profile..."
    execute_profile profile
  else
    profile = profile.downcase
    puts "Executing #{profile} profile..."
    execute_profile profile
  end
else
  execute_profile ARGV[0]
end
