#!/usr/bin/env ruby

begin
  config = File.open("KeetConf").read
rescue
  puts "No KeetConf file found."
  exit 1
end

eval(config)

def execute_profile(profile)
  platform = `uname -s`.strip
  profiles = COMMANDS.keys
  commands = COMMANDS.map { |key, value| [key.downcase, value] }

  if profiles.include? profile
    COMMANDS[profile].keys.each do |os|
      next if os == "description"
      if /#{os}/.match(platform)
        COMMANDS[profile][os].each do |cmd|
          puts "=> #{cmd}\n"
          begin
            system(cmd, exception: true)
          rescue Exception => e
            e.message["Command failed"] = "\e[41m COMMAND FAILED \e[0m"
            puts "\n#{e.message}"
            exit 1
          end
        end
      end
    end
  else
    puts "Invalid profile..."
  end
end

if ARGV.length == 0
  commands = COMMANDS.map { |key, value| [key.downcase, value] }
  PROFILES = COMMANDS.keys

  puts GREET
  puts "What profile would you like to use?\n\n"
  PROFILES.each_with_index do |profile, index|
    puts "#{index} -> #{profile}"
  end

  print "\nProfile -> "
  profile = gets.strip

  if /([A-Z])\w+/.match(profile) != ""
    profile = PROFILES[profile.to_i].downcase
    puts "Executing #{profile} profile..."
    execute_profile profile
  else
    profile = profile.downcase
    puts "Executing #{profile} profile..."
    execute_profile profile
  end
else
  execute_profile ARGV[0]
end
