#!/usr/bin/env ruby

begin
  config = File.open(".keet").read
rescue
  puts "No .keet file found."
end

eval(config)

def execute_profile(profile)
  os = `uname -s`.strip
  profiles = PROFILES.map(&:downcase)
  commands = COMMANDS.map { |key, value| [key.downcase, value] }

  if profiles.include? profile
    if COMMANDS[profile].has_key? os
      COMMANDS[profile][os].each do |command|
        puts "\n=> %s" % [command]
        begin
          cmd = system(command, exception: true)
        rescue Exception => e
          puts "\n\e[41m COMMAND FAILED \e[0m -> '#{e.message}'"
          exit 1
        end
      end
    else
      puts "Unsupported platform"
    end
  else
    puts "Invalid profile..."
  end
end

if ARGV.length == 0
  puts GREET
  puts "What profile would you like to use?\n\n"
  puts PROFILES

  print "\nProfile -> "
  profile = gets
  profile = profile.downcase.strip
  puts "Executing %s profile..." % [profile]
  execute_profile profile
else
  execute_profile ARGV[0]
end
